[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
remappings = ["forge-std-1.9.7/=dependencies/forge-std-1.9.7/"]
fs_permissions = [
    { access = "read-write", path = "./dumpStates" },
]

[dependencies]
forge-std = "1.9.7"

[soldeer]
recursive_deps = true
remappings_location = "config"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
